name: Push & Pull Request

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  prepare_branch:
    name: Prepare branch
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: CI
        run: npm run build:ci

